server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      key-deserializer: "org.apache.kafka.common.serialization.IntegerDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      group-id: "learn-aggregator"
    properties:
      spring.json.trusted.packages: "com.selivanov.dto"

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/learn_base
    username: pg
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true