spring:
  #  profile: inMemory
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=authentication
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: update

jwt:
  config:
    secret: 'c2VjcmV0X3NlY3JldF9zZWNyZXRfc2VjcmV0X3NlY3JldA=='
    tokenExpirationMs: 60_000
    refreshTokenExpirationMs: 3600_000
    #  15min - 2h
    #  1min = 60s = 60_000ms
    # 10min = 600_000ms
    # 60 min 3600_000ms
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect