spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/learn_base
    username: pg
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 2

#server:
#  port: 8081