spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/learn_base
    username: pg
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

#server:
#  port: 8081