kafka:
  topics:
    student-request: student-info-topic
    student-response: student-async-result

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.IntegerSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
    consumer:
      key-deserializer: "org.apache.kafka.common.serialization.IntegerDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      group-id: "learn-aggregator"
    properties:
      spring.json.trusted.packages: "*"

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/learn_base
    username: pg
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
#    baseline-on-migrate: true
#    baseline-version: 2
jwt:
  config:
    secret: 'c2VjcmV0X3NlY3JldF9zZWNyZXRfc2VjcmV0X3NlY3JldA=='
    tokenExpirationMs: 60_000
    refreshTokenExpirationMs: 3600_000

clients:
  university: "http://localhost:8080"
  username: "Bob"
  password: "secret123"